import { SalesChannel } from '../enums/sales-channel.enum';
import { InvoiceStatus } from '../enums/invoice-status.enum';

/**
 * Sales Invoice Model (Generated by Invoice Engine)
 */
export interface SalesInvoice {
  id?: number;
  invoiceNumber: string;
  invoiceDate: string;
  
  // Order Reference
  customerOrderId: number;
  orderNumber?: string;
  salesChannel: SalesChannel;
  
  // Customer Information
  customerId: number;
  customerName: string;
  customerAddress?: string;
  customerPhone?: string;
  customerTaxNumber?: string;
  customerNationalId?: string;
  
  // Vehicle Information
  vehicleId: number;
  vehicleVin: string;
  vehicleMake: string;
  vehicleModel: string;
  vehicleYear: number;
  vehicleColor?: string;
  vehicleChassisNumber?: string;
  
  // Financial Details
  basePrice: number;
  additionalCharges: number;
  discountAmount: number;
  subtotal: number;
  vatPercentage: number;
  vatAmount: number;
  totalAmount: number;
  
  // Payment Information
  advancePaymentAmount: number;
  remainingBalance: number;
  paymentStatus: 'Unpaid' | 'PartiallyPaid' | 'Paid';
  
  // Ledger Routing (Double Entry)
  debitAccountType: number; // 1=Cash, 2=Clients, 4=Banks
  debitAccountId?: number;
  creditSalesAccountType: number; // 12=Sales
  creditTaxAccountType: number; // 18=Tax
  
  // ZATCA Compliance
  zatcaQrCode?: string; // Base64 encoded TLV
  zatcaInvoiceHash?: string;
  zatcaUuid?: string;
  companyVatNumber?: string;
  companyName?: string;
  
  // Status and Workflow
  status: InvoiceStatus;
  approvalRequired: boolean;
  approvalWorkflowId?: number;
  approvedBy?: string;
  approvalDate?: string;
  
  // Delivery Information
  deliveryStatus: 'Pending' | 'ReadyForDelivery' | 'Delivered';
  deliveryDate?: string;
  deliveryReceivedBy?: string;
  
  // Metadata
  notes?: string;
  internalNotes?: string;
  createdBy?: string;
  createdDate: string;
  lastUpdated?: string;
  
  // Related Documents
  attachments?: string[];
}

/**
 * DTO for processing order to invoice
 */
export interface ProcessOrderToInvoiceDto {
  customerOrderId: number;
  invoiceDate?: string;
  notes?: string;
}

/**
 * Invoice generation result
 */
export interface InvoiceGenerationResult {
  success: boolean;
  invoice?: SalesInvoice;
  errors?: string[];
  warnings?: string[];
  requiresApproval: boolean;
  approvalReason?: string;
}

/**
 * Ledger entry model (for double-entry bookkeeping)
 */
export interface LedgerEntry {
  accountType: number;
  accountId?: number;
  accountName: string;
  debitAmount: number;
  creditAmount: number;
  description: string;
  referenceType: 'SalesInvoice';
  referenceId: number;
  entryDate: string;
}

/**
 * ZATCA QR Code data structure
 */
export interface ZatcaQrData {
  companyName: string;
  vatNumber: string;
  timestamp: string;
  totalAmount: number;
  vatAmount: number;
}

/**
 * Invoice approval request
 */
export interface InvoiceApprovalRequest {
  invoiceId: number;
  requestedBy: string;
  reason: string;
  priority: 'Low' | 'Medium' | 'High';
}

/**
 * Payment recording DTO
 */
export interface RecordPaymentDto {
  invoiceId: number;
  paymentAmount: number;
  paymentDate: string;
  paymentMethod: 'Cash' | 'BankTransfer' | 'Check' | 'Card';
  referenceNumber?: string;
  bankId?: number;
  notes?: string;
}

/**
 * Delivery confirmation DTO
 */
export interface ConfirmDeliveryDto {
  invoiceId: number;
  deliveryDate: string;
  receivedBy: string;
  receivedByNationalId?: string;
  notes?: string;
}
